import type { Metadata } from "next";
import LegalPage, { Clause, Points } from "@/components/legal/LegalPage";

export const metadata: Metadata = {
  title: "Privacy",
  description: "What Dinka stores, why it stores it, and how to get rid of it.",
};

/**
 * Written from what the application actually does — the Prisma schema, the auth
 * configuration and the upload paths — rather than from a template. Nothing here
 * describes a practice the code does not have.
 */
export default function Page() {
  return (
    <LegalPage
      title="Privacy"
      updated="13 September 2026"
      intro="This is a plain-language description of what Dinka stores, why, and how to get rid of it. It covers the product as it is built today; if that changes, this page changes with it."
    >
      <Clause title="What we store">
        <p>Only what the product needs to work:</p>
        <Points
          items={[
            "Your account: email address, and either a password we store as a bcrypt hash or the fact that you signed in with Google. We never hold a readable copy of your password.",
            "Your profile: display name, handle, bio, pronouns, location, website and pictures — all of it optional except the name, and all of it visible to anyone who opens your profile.",
            "What you post: posts, stories, reels, comments, reactions, poll votes, bookmarks and the accounts you follow or block.",
            "Your messages: direct messages are stored so a conversation is still there when you come back. They are not end-to-end encrypted.",
            "Counts: views on your posts and the time you were last active, which is what drives the insights on your own profile and the online dot on someone else's.",
          ]}
        />
      </Clause>

      <Clause title="What we do not do">
        <Points
          items={[
            "We do not sell your data.",
            "We do not put advertising in the feed.",
            "We do not build a profile of you from activity on other sites.",
            "We do not read your direct messages to target anything at you.",
          ]}
        />
      </Clause>

      <Clause title="Who else touches it">
        <p>
          Dinka runs on services that necessarily see some of your data in order to do their job:
        </p>
        <Points
          items={[
            "A hosted PostgreSQL database, which holds everything described above.",
            "Cloudinary, which stores and serves the images and video you upload.",
            "Google, if you choose to sign in with a Google account.",
            "An email provider, which delivers the verification code when you sign up.",
            "A signalling server, which passes the connection details for voice and video calls. Call audio and video travel directly between the two of you where the network allows it.",
          ]}
        />
        <p>
          Posts marked <em>Followers</em> are served only to accounts that follow you. Posts marked{" "}
          <em>Public</em> can be seen by anyone with an account.
        </p>
      </Clause>

      <Clause title="AI-written posts">
        <p>
          Some posts on Dinka are generated by Google&apos;s Gemini model to keep a new feed from
          being empty. They are labelled <em>AI</em> everywhere they appear and are never presented
          as a person. Your posts are not sent to that model.
        </p>
      </Clause>

      <Clause title="Cookies">
        <p>
          One cookie, holding your signed-in session. There are no analytics or advertising cookies.
          Your theme choice is kept in your browser&apos;s local storage and never reaches us.
        </p>
      </Clause>

      <Clause title="Deleting your account">
        <p>
          Settings → Account → Delete account removes your account along with your posts, messages,
          stories and follow relationships. It is immediate and cannot be undone. Copies may survive
          briefly in routine backups before they age out.
        </p>
      </Clause>

      <Clause title="Children">
        <p>Dinka is not intended for anyone under 13.</p>
      </Clause>
    </LegalPage>
  );
}
