name: Push to GC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧱 Checkout repository
        uses: actions/checkout@v3

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 🔍 Install dependencies & build
        run: |
          npm ci
          npm run build

      - name: 🚀 Deploy to GCP VM (Raw SSH)
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem dkjdi@$SSH_HOST << 'EOF'
            cd ~/dinka
            git pull origin main
            npm ci
            npm run build
            pm2 restart next-js1
          EOF

          rm -f private_key.pem
